--


- name: Ansible delete multiple file example
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/hive 
    - /usr/local/hadoop
    - /usr/local/spark
    - /usr/local/presto
    - /usr/local/hbase
    - /home/{{ cluster_user }}/hadoop-data
    - /home/{{ cluster_user }}/hive-metastore
    - /home/{{ cluster_user }}/zeppelin


# cassandra ?
# rm -fr
