---

- name: delete multiple dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/hive 
    - /usr/local/hadoop
    - /usr/local/spark
    - /usr/local/presto
    - /usr/local/hbase
    - /home/{{ cluster_user }}/hadoop-data
    - /home/{{ cluster_user }}/hive-metastore
    - /home/{{ cluster_user }}/zeppelin
    - /var/lib/cassandra/commitlog  
    - /var/lib/cassandra/data
    - /var/lib/cassandra/hints 
    - /var/lib/cassandra/saved_caches
 

# cassandra ?
# rm -fr
