---

- include_vars: "{{ nodesfile }}"

#- vars:

#
- name: replace default config
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: "cassandra.yaml", dest: "/etc/cassandra/cassandra.yaml"}


# ajouter le service dans systemctl pour redemarrage?

