---

- include_vars: "{{ nodesfile }}"
- set_fact: zep_v="0.7.3-bin-all"
#- set_fact: zep_root="/home"
###- set_fact: zep_v="0.8.0-SNAPSHOT"

- name: unpack zeppelin
  unarchive: src=./roles/zeppelin/files/zeppelin-{{ zep_v }}.tgz dest={{ zep_root }}/{{ cluster_user}} owner={{ cluster_user}} group={{ cluster_group }} creates={{ zep_root }}//{{ cluster_user}}/zeppelin

- command: mv /home/{{ cluster_user}}/zeppelin-{{ zep_v }} {{ zep_root }}//{{ cluster_user}}/zeppelin creates={{ zep_root }}//{{ cluster_user}}/zeppelin removes={{ zep_root }}//{{ cluster_user}}/zeppelin-{{ zep_v }}



#- name: stop zepelin daemon
#  shell : "{{ zep_root }}/{{ hadoop_user}}/zeppelin/bin/zeppelin-daemon.sh stop"

- name: Add the service scripts
  template: src={{ item.src }} dest={{ item.dest }} owner={{ cluster_user}} group={{ cluster_group }}
  with_items:
    - {src: "zeppelin-site.xml.template", dest: "{{ zep_root }}//{{ cluster_user}}/zeppelin/conf/zeppelin-site.xml" }
    - {src: "zeppelin-env.sh.template", dest: "{{ zep_root }}//{{ cluster_user}}/zeppelin/conf/zeppelin-env.sh" }

##- name: start zepelin daemon
##  shell : /home//{{ hadoop_user}}/zeppelin/bin/zeppelin-daemon.sh start

