---


- name: Install zep on frontend node
  hosts: master
  remote_user: hadoop
  sudo: no
  vars_files:
    - roles/vars/os
    - vars/zep.vars
    - roles/vars/openstack
  roles:
#    - common1
    - zeppelin


