---



- name: Install presto on master node
  hosts: master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - presto
  vars:
   presto_role: master
   presto_data_path: /home/ubuntu/presto-data


- name: Install presto on master node
  hosts: slaves
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - presto
  vars:
   presto_role: slave
   presto_data_path: /home/ubuntu/presto-data

