---


- name: Install zep on frontend node
  hosts: master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - vars/zep.vars
    - roles/vars/openstack
  roles:
    - zeppelin
    - nginx


