---



- name: Install cassandra on slave
  hosts: master,slaves
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
    - vars/cassandra.vars

  roles:
    - cassandra

#- name: Install cassandra frontend node
#  hosts: hadoop-master
#  remote_user: hadoop
#  sudo: yes
#  vars_files:
#    - roles/vars/os
#    - roles/vars/openstack
#    - cassandra.vars
#  roles:
#    - cassandra

