---



- name: Install hive on frontend node
  hosts: cluster-master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
    - vars/hive.vars
  roles:
    - hive


# fait par le master apres les autres?
#- name: Start services
#  hosts: hadoop-master
#  remote_user: hadoop
#  sudo: no
#  vars_files:
#    - roles/vars/os
#
#  roles:
#    - hivestart

