---



- name: Install hive on frontend node
  hosts: master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
    - vars/hive.vars
  roles:
    - hive



