#!/usr/bin/env ansible-playbook
---

- name: Destroy nodes
  hosts: localhost
  vars_files:
    - vars/provision.vars




  tasks:

  - name: Connect to the IREQ Cloud
    os_auth:

  - debug: var=groups['slaves']
#  - debug: var=groups

  - name: Destroy instances
    os_server:
      name: "{{ item }}"
      state: absent
    with_items: "{{ groups['slaves'] }}"
