---


- name: Install platform bin on master node
  hosts: master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - common
    - ssh
    - master

- name: Install platform bin on cluster nodes
  hosts: slaves
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - common
    - ssh
    - ntp

- name: configure main hadoop
  hosts: master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - hadoopinit

