---



- name: Start cassandra service
  hosts: slaves,master
  remote_user: hadoop
  sudo: yes
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
    - vars/cassandra.vars
  roles:
    - cassandrastart

#- name: Install cassandra frontend node
#  hosts: hadoop-master
#  remote_user: hadoop
#  sudo: yes
#  vars_files:
#    - roles/vars/os
#    - cassandra.vars
#    - roles/common/vars/main.yml
#  roles:
#    - cassandra

