---



# fait par le master apres les autres?
- name: Manage Hbase service
  hosts: master
  remote_user: hadoop
  sudo: no
  vars:
    - cmd: "{{ commande }}"
  vars_files:
    - roles/vars/os

  roles:
    - hbasestart

