---



# fait par le master apres les autres?
- name: Start services
  hosts: hadoop-master
  remote_user: hadoop
  sudo: no
  vars:
    - cmd: "{{ cmd }}"
  vars_files:
    - roles/vars/os

  roles:
    - hbasestart

