---



- name: Start presto service on cluster
  hosts: slaves,master
  remote_user: hadoop
  sudo: yes
  vars:
    - cmd: "{{ commande }}"
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
  roles:
    - prestostart

