---



# fait par le master apres les autres?
- name: Start services
  hosts: master
  remote_user: hadoop
  sudo: no
  vars_files:
    - roles/vars/os
    - roles/vars/openstack
    - vars/zep.vars
  roles:
    - zeppelinstart

